name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby (version 3.1)
        run: |
          brew install ruby@3.1
          echo 'export PATH="/usr/local/opt/ruby@3.1/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile

      - name: Install CocoaPods
        run: |
          gem install cocoapods

      - name: Install dependencies
        run: |
          pod install

      - name: Build the app
        run: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -configuration Debug
